;(function ($) {
    var blocks = [{
        // Block 1
        delay: 300,
        instructions: [
            "The two categories you must distinguish are:\n\n",
            "UNPLEASANT vs. PLEASANT  words.\n\n",
            "Press the \"a\" key if the stimulus is an UNPLEASANT word.\n",
            "Press the \"k\" key if the stimulus is a PLEASANT word.\n\n",
            "Please place your hands on the keyboard now, so that you can ",
            "press the \"a\" key with your left hand,",
            "and the \"k\" key with your right hand.\n\n",
            "Make sure that your hands are positioned correctly because only \"a\" and",
            " \"k\" will be recognized by the program.\n"].join(""),
        leftWord: "unpleasant",
        rightWord: "plesant",
        targetWords: [
            {word: "party", correct: "R"},
            {word: "disease", correct: "L"},
            {word: "smile",  correct: "R"},
            {word: "friend", correct: "R"},
            {word: "joy", correct: "R"},
            {word: "happy", correct: "R"},
            {word: "cockroach", correct: "L"},
            {word: "sunshine", correct: "R"},
            {word: "garbage", correct: "L"},
            {word: "death", correct: "L"},
            {word: "love", correct: "R"},
            {word: "agony", correct: "L"},
            {word: "pain", correct: "L"},
            {word: "evil", correct: "L"},
            {word: "gift", correct: "R"},
            {word: "holiday", correct: "R"},
            {word: "warmth", correct: "R"},
            {word: "vomit", correct: "L"},
            {word: "disaster", correct: "L"},
            {word: "stink", correct: "L"}]
    }, {
        // Block 2
        delay: 300,
        instructions: [
		    "The next two categories that you are to distinguish are:\n\n",
		    "SELF vs. OBJECT words.\n\n",
		    "Press the \"a\" key if the stimulus is a SELF word.\n",
		    "Press the \"k\" key if the stimulus is an OBJECT word.\n\n",
		    "Please place your hands on the keyboard now, so that you can ",
		    "press the \"a\" key with your left hand,",
            "and the \"k\" key with your right hand.\n\n"].join(""),
        leftWord: "self",
        rightWord: "object",
        targetWords: [
            {word: "me", correct: "L", count: "4"},
            {word: "myself", correct: "L", count: "4"},
            {word: "it", correct: "R", count: "4"},
            {word: "that", correct: "R", count: "4"}]
    }, {
        // Block 3
        delay: 300,
        instructions: [
		    "The four categories that you are to distinguish are:\n\n",
		    "UNPLEASANT vs. PLEASANT words.\n",
		    "OR\n",
		    "SELF vs. OBJECT words.\n\n",
		    "Press the \"a\" key if the stimulus is an UNPLEASANT word OR a SELF word.\n",
		    "Press the \"k\" key if the stimulus is a PLEASANT word OR an OBJECT word.\n\n",
		    "Please place your hands on the keyboard now, so that you can ",
		    "press the \"a\" key with your left hand,",
            "and the \"k\" key with your right hand.\n\n"].join(""),
        leftWord: "unpleasant\nor self",
        rightWord: "pleasant\nor object",
        targetWords: [
            {word: "party", correct: "R"},
            {word: "disease", correct: "L"},
            {word: "smile", correct: "R"},
            {word: "friend", correct: "R"},
            {word: "joy", correct: "R"},
            {word: "happy", correct: "R"},
            {word: "cockroach", correct: "L"},
            {word: "sunshine", correct: "R"},
            {word: "garbage", correct: "L"},
            {word: "death", correct: "L"},
            {word: "love", correct: "R"},
            {word: "agony", correct: "L"},
            {word: "pain", correct: "L"},
            {word: "evil", correct: "L"},
            {word: "gift", correct: "R"},
            {word: "holiday", correct: "R"},
            {word: "warmth", correct: "R"},
            {word: "vomit", correct: "L"},
            {word: "disaster", correct: "L"},
            {word: "stink", correct: "L"},
            {word: "me", correct: "L", count: "4"},
            {word: "myself", correct: "L", count: "4"},
            {word: "it", correct: "R", count: "4"},
            {word: "that", correct: "R", count: "4"}]
    }, {
        // Block 4
        delay: 300,
        instructions: [
		    "The next two categories that you are to distinguish are:\n\n",
		    "OBJECT vs. SELF words.\n\n",
		    "Press the \"a\" key if the stimulus is an OBJECT word.\n",
		    "Press the \"k\" key if the stimulus is a SELF word.\n\n",
		    "Please place your hands on the keyboard now, so that you can ",
		    "press the \"a\" key with your left hand,",
            "and the \"k\" key with your right hand.\n\n"].join(""),
        leftWord: "object",
        rightWord: "self",
        targetWords: [
            {word: "me", correct: "R", count:"4"},
            {word: "myself", correct: "R", count:"4"},
            {word: "it", correct: "L", count:"4"},
            {word: "that", correct: "L", count:"4"}]
    }, {
        // Block 5
        delay: 300,
        instructions: [
		    "The four categories that you are to distinguish are:\n\n",
		    "UNPLEASANT vs. PLEASANT words.\n",
		    "OR\n",
		    "OBJECT vs. SELF words.\n\n",
		    "Press the \"a\" key if the stimulus is an UNPLEASANT word OR an OBJECT word.\n",
		    "Press the \"k\" key if the stimulus is a PLEASANT word OR an SELF word.\n\n",
		    "Please place your hands on the keyboard now, so that you can ",
		    "press the \"a\" key with your left hand,",
            "and the \"k\" key with your right hand.\n\n"].join(""),
        leftWord: "unpleasant\nor object",
        rightWord: "pleasant\nor self",
        targetWords: [
            {word: "party", correct: "R"},
            {word: "disease", correct: "L"},
            {word: "smile", correct: "R"},
            {word: "friend", correct: "R"},
            {word: "joy", correct: "R"},
            {word: "happy", correct: "R"},
            {word: "cockroach", correct: "L"},
            {word: "sunshine", correct: "R"},
            {word: "garbage", correct: "L"},
            {word: "death", correct: "L"},
            {word: "love", correct: "R"},
            {word: "agony", correct: "L"},
            {word: "pain", correct: "L"},
            {word: "evil", correct: "L"},
            {word: "gift", correct: "R"},
            {word: "holiday", correct: "R"},
            {word: "warmth", correct: "R"},
            {word: "vomit", correct: "L"},
            {word: "disaster", correct: "L"},
            {word: "stink", correct: "L"},
            {word: "me", correct: "R", count: "4"},
            {word: "myself", correct: "R", count: "4"},
            {word: "it", correct: "L", count: "4"},
            {word: "that", correct: "L", count: "4"}]
    }];
}(window.jquery));
